# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      pwd
      ls -l
- task: OcConditionalCmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-3.11-opentlc'
    version: 'v3.11.0'
    cmd: 'oc get buildconfigs -n $(PROJECT_NAME)'
    condition: 'exists'
    resource: 'buildconfigs/$(APPLICATION_NAME)'
- task: oc-cmd@2
  displayName: 'Start OCP build'
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-3.11-opentlc'
    version: 'v3.11.0'
    cmd: 'oc start-build $(APPLICATION_NAME) --from-dir=/home/vsts/work/1/s/TodoAPI-NetCore/bin/Debug/netcoreapp3.1/ --wait --follow -n $(PROJECT_NAME)'
