# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-cmd@2
  displayName: 'Build OCP'
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-3.11-opentlc'
    version: 'v3.11.0'
    cmd: |
      oc get bc -n netcore-s2i-poc
      oc get is -n netcore-s2i-poc
- task: OcConditionalCmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'openshift-3.11-opentlc'
    version: 'v3.11.0'
    cmd: 'oc get bc -n netcore-s2i-poc'
    condition: 'exists'
    resource: 'todo-api'